---
- name: Prepare Kubernetes Nodes for Cluster bootstrapping
  hosts: k8snodes
  become: yes
  roles:
    - kubernetes-bootstrap

- name: Initialize Kubernetes Control Plane
  hosts: k8smaster
  become: yes
  tasks:
    - name: Run kubeadm init with control plane endpoint
      command: >
        kubeadm init
        --control-plane-endpoint={{ control_plane_endpoint }}
        --pod-network-cidr={{ pod_network_cidr }}
        --cri-socket={{ cri_socket }}
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Set up kubeconfig for admin
      block:
        - name: Create .kube directory
          file:
            path: /home/{{ ansible_user }}/.kube
            state: directory
            mode: 0755
            owner: "{{ ansible_user }}"
        - name: Copy admin.conf
          copy:
            src: /etc/kubernetes/admin.conf
            dest: /home/{{ ansible_user }}/.kube/config
            remote_src: yes
            mode: 0644
            owner: "{{ ansible_user }}"

    - name: Apply Calico network plugin manifest
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/calico.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Save join command to file
      copy:
        content: "{{ join_cmd.stdout }}"
        dest: /tmp/kubeadm_join_command.sh
        mode: 0755
    - name: Generate full join command with certificate key
      shell: |
        kubeadm token create --print-join-command --certificate-key $(kubeadm init phase upload-certs --upload-certs | tail -1)
      register: control_plane_join_cmd
      changed_when: false

    - name: Save control plane join command to file
      copy:
        content: "{{ control_plane_join_cmd.stdout }}"
        dest: /tmp/control_plane_join.sh
        mode: 0755

- name: Join other master nodes to the control plane
  hosts: k8smasters[1:]
  become: yes
  tasks:
    - name: Fetch join command script from first master
      fetch:
        src: /tmp/control_plane_join.sh
        dest: /tmp/control_plane_join.sh
        flat: yes
      delegate_to: "{{ groups['k8smasters'][0] }}"
      run_once: true

    - name: Copy join script to this master
      copy:
        src: /tmp/control_plane_join.sh
        dest: /tmp/control_plane_join.sh
        mode: 0755

    - name: Join this node as control plane
      command: bash /tmp/control_plane_join.sh
      args:
        creates: /etc/kubernetes/kubelet.conf

- name: Join Worker Nodes to the Cluster
  hosts: k8sworkers
  become: yes
  tasks:
    - name: Fetch join command from control plane
      fetch:
        src: /tmp/kubeadm_join_command.sh
        dest: /tmp/kubeadm_join_command.sh
        flat: yes
      delegate_to: "{{ groups['k8smasters'][0] }}"
      run_once: true

    - name: Copy join script to workers
      copy:
        src: /tmp/kubeadm_join_command.sh
        dest: /tmp/kubeadm_join_command.sh
        mode: 0755

    - name: Join the cluster
      command: bash /tmp/kubeadm_join_command.sh
      args:
        creates: /etc/kubernetes/kubelet.conf
